name: Build docker image and push to ecr

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      branch:
        description: 'The branch to deploy'
        required: true
        type: string

jobs:
  ecr-build-push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}   

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up .npmrc
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "@ignidus:registry=https://npm.pkg.github.com/ignidus" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> .npmrc
  
      - name: Build and tag image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          DOCKER_BUILDKIT=1 docker build . -t $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG -t $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:latest --secret id=npmrc,src=./.npmrc
          echo "image=$ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}" >> $GITHUB_OUTPUT
  
      - name: Remove .npmrc file
        run: rm ./.npmrc
  
      - name: Scan docker image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:latest
          fail-build: false
          severity-cutoff: high
          output-format: table
  
      - name: Push image to Amazon ECR
        run: docker push ${{ steps.build-image.outputs.image }} --all-tags