name: Deploy to ECS

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      branch:
        description: 'The branch to deploy'
        required: true
        type: string

jobs:
  ecs-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Get JWT secret from AWS Secrets Manager
        run: |
          aws secretsmanager get-secret-value --secret-id ${{ vars.JWT_SECRET_NAME }} --region ${{ vars.AWS_REGION }} --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' >> ${{ inputs.environment }}.env

      - name: Download parameters
        run: |
          aws ssm get-parameter \
            --name ${{ vars.PARAMETER_STORE_VAR_NAME }} \
            --output text \
            --query 'Parameter.Value' >> ${{ inputs.environment }}.env

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ vars.ECS_SERVICE }} \
          --query taskDefinition > ${{ vars.ECS_TASK_DEFINITION }}
  
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: ignidus/amazon-ecs-render-task-definition@v2
        with:
          task-definition: ${{ vars.ECS_TASK_DEFINITION }}
          container-name: ${{ vars.CONTAINER_NAME }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:latest
          environment-files: |
            ./${{ inputs.environment }}.env

      - name: Remove env file
        run: rm ./${{ inputs.environment }}.env
  
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ vars.ECS_SERVICE }}
          cluster: ${{ vars.ECS_CLUSTER }}
          wait-for-service-stability: true