name: Production Deployment

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  unit-test:
    uses: ./.github/workflows/unit-tests.yml
    with:
      environment: production
      branch: ${{ github.ref_name }}

  build:
    needs: 
      - unit-test
    uses: ./.github/workflows/build-docker-image.yml
    secrets: inherit
    with:
      environment: production
      branch: ${{ github.ref_name }}

  deploy:
    needs: 
      - build
    uses: ./.github/workflows/deploy-to-ecs.yml
    secrets: inherit
    with:
      environment: production
      branch: ${{ github.ref_name }}
