// TODO: there may be more of these
export type RuleType =
    | 'compare'
    | 'list_compare'
    | 'atoi_compare'
    | 'date_compare'
    | 'bool_compare'
    | 'ratio_compare'
    | 'growth_compare'
    | 'change_compare'
    | 'json_compare'
    | 'json_count'
    | 'minor_change'
    | 'question_check'
    | 'question_multiselect_check'
    | 'cab_data_factors'
    | 'iss_score'
    | 'dot_rating'
    | 'history_question_check'
    | 'includes_check'
    | 'endorsement_check'
    | 'classcode_check'
    | 'license_check'
    | 'equipment_check'
    | 'string_search'
    | 'dissallow_all_classcodes_not_explicitly_allowed';
