name: Clear NPM Cache

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  clear-npm-cache:
    runs-on: ubuntu-latest
    steps:
    - name: Clear GitHub Actions cache
      run: |
        gh api -X DELETE /repos/${{ github.repository }}/actions/caches --silent