name: Clear NPM Cache

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  clear-npm-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear GitHub Actions cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache delete --all --repo ${{ github.repository }}
