name: Development Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:       
  unit-test:
    uses: ./.github/workflows/unit-tests.yml
    with:
      environment: development
      branch: ${{ github.ref_name }}
  
  deploy:
    needs: unit-test
    uses: ./.github/workflows/deploy-to-ecs.yml
    secrets: inherit
    with:
      environment: development
      branch: ${{ github.ref_name }}

  create-release:
    needs: deploy
    permissions:
      contents: write
      packages: write
      issues: write
    uses: ./.github/workflows/create-release.yml
    with:
      environment: development
      branch: ${{ github.ref_name }}
