name: Unit tests

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      branch:
        description: 'The branch to deploy'
        required: true
        type: string

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        
    - name: Install private GitHub package
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@ignidus'

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm i
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run unit tests
      run: npm run test
